DROP TABLE IF EXISTS playlist;
DROP TABLE IF EXISTS music;
DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS admin;


CREATE TABLE Music (
	m_code	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	m_title	VARCHAR(30)	NOT NULL,
	m_singer VARCHAR(20)	NOT NULL,
	m_date	DATE	NOT NULL,
	m_album	VARCHAR(20)	NOT NULL
);

CREATE TABLE Member (
	m_id	VARCHAR(20)	NOT NULL PRIMARY KEY,
	m_pwd	VARCHAR(20)	NOT NULL,
	m_name	VARCHAR(20)	NOT NULL,
	m_age	INT	NOT NULL
);

CREATE TABLE Admin (
	a_id	VARCHAR(20)	NOT NULL PRIMARY KEY,
	a_pwd	VARCHAR(20)	NOT NULL
);

CREATE TABLE PlayList (
	p_code	INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	m_id	VARCHAR(20)	NOT NULL,
	m_code	INT	NOT NULL
);

ALTER TABLE plum.PlayList 
ADD CONSTRAINT m_id
FOREIGN KEY (m_id)
REFERENCES plum.member (m_id)
ON DELETE CASCADE
ON UPDATE CASCADE,
ADD CONSTRAINT m_code
FOREIGN KEY (m_code)
REFERENCES plum.Music (m_code)
ON DELETE CASCADE
ON UPDATE CASCADE;


INSERT INTO Music VALUES (DEFAULT, 'After LIKE','IVE(아이브)','2022-08-22','After LIKE');
INSERT INTO Music VALUES (DEFAULT, 'Shut Down','BLACKPINK','2022-09-16','BORN PINK');
INSERT INTO Music VALUES (DEFAULT, 'Hype boy','NewJeans','2022-08-01','New Jeans');
INSERT INTO Music VALUES (DEFAULT, 'Rush Hour','Crush','2022-09-22','Rush Hour');
INSERT INTO Music VALUES (DEFAULT, 'Attention','NewJeans','2022-08-01','New Jeans');
INSERT INTO Music VALUES (DEFAULT, 'Pink Venom','BLACKPINK','2022-09-16','BORN PINK');
INSERT INTO Music VALUES (DEFAULT, 'LOVE DIVE','IVE(아이브)','2022-04-05','LOVE DIVE');
INSERT INTO Music VALUES (DEFAULT, 'Monologue','Tei(테이)','2022-09-18','Monologue');
INSERT INTO Music VALUES (DEFAULT, 'TOMBOY','(여자)아이들','2022-03-14','I NEVER DIE');
INSERT INTO Music VALUES (DEFAULT, 'RUN','Leellamarz(릴러말즈)','2020-06-23','RUN');
INSERT INTO Music VALUES (DEFAULT, 'Trip','Leellamarz(릴러말즈)','2018-09-10','Trip');
INSERT INTO Music VALUES (DEFAULT, 'TWINTAIL20','디핵(D-Hack)','2020-03-21','TWINTAIL20');

INSERT INTO member VALUES("jun", "jun1", "전아름", 25);
INSERT INTO member VALUES('test01',1234,'테스트',25);
INSERT INTO admin VALUES('admin1' , 'admin123');



COMMIT;
